### PR TITLE
Added documents support for CC and clubs

### PR DESCRIPTION
**Pull request by bhavberi**

### CODE REVIEW

**Review by bhavberi — COMMENTED** [review]
Use Datagrid in place of plain in the DocsList Table (to maintain consistency across the app)

**Comment by bhavberi** [comment]
Need to remove the error on big image file.

**Comment by abhiramtilakiiit** [comment]
> Need to remove the error on big image file.

will be done once the Other PR about filles will be merged, until then we can stall this

**Comment by bhavberi** [comment]
> > Need to remove the error on big image file.
> 
> will be done once the Other PR about fille compression will be merged, until then we can stall this

Change it to warning for now. Will change that once file compression is added.

**Review by bhavberi — COMMENTED** [review]
Everything in this PR done. To be tested once by @abhiramtilakiiit

**Pull request merged**
