### PR TITLE
Fix imageupload adds important features like file compression

### PR DESCRIPTION
**Pull request by abhiramtilakiiit**
## Changes:

- Adds a file compression for images with a limit with 0.3 Mb. Resized images will have the
  `resized_` prefix.
- Adds a new attribute filename for `uploadFile()`, which allows custom filenames
  for members nad clubs.
- Adds a new attribute `shape` to fileUpload component.
- Fixes the aspect ratios in the club banners

### CODE REVIEW

**Review by bhavberi — APPROVED** [review]
Check with @Dileepadari as well before merging

**Comment by bhavberi** [comment]
And while merging, make sure to select the option fo Squah & merge, as there are a lot of small commits in this PR

**Review by Dileepadari — CHANGES_REQUESTED** [review]
we are trying to use browser-only packages (browser-image-resizer) in an environment that doesn't have access to browser-specific globals like window and self. which is giving error in logs, 

solution:
// Dynamically import browser-image-resizer since it's only needed on the client side

import dynamic from 'next/dynamic';
const readAndCompressImage = dynamic(() =>
  import('browser-image-resizer').then((mod) => mod.readAndCompressImage),
  { ssr: false }
);

 everything other than this is good and working, have done multiple tests.

**Review by Dileepadari — APPROVED** [review]
LGTM

**Review by bhavberi — APPROVED** [review]

**Comment by Dileepadari** [comment]
verified

**Comment by abhiramtilakiiit** [comment]
@Dileepadari, @bhavberi  can you check once. This is not working!!!. The resizedBlob.size just returns undefined

**Comment by bhavberi** [comment]
As per PR #120, we have moved the image resizing to backend.

**Pull request merged**
