### PR TITLE
added initial pagination, issue with the updation of states without l…

### PR DESCRIPTION
**Pull request by Dileepadari**
initial pagination code uploaded

### CODE REVIEW

**Comment by Dileepadari** [comment]
Attached pr in events repo: [https://github.com/Clubs-Council-IIITH/events/pull/46](Events)

**Comment by bhavberi** [comment]
Have made changed in the events PR. @Dileepadari Please update this PR Accordingly

Also, how are we handling searching/club selection in pagination, when all of the events are not even loaded? A question need to be thought about and fixed, before completion/merging of this PR

**Review by bhavberi — APPROVED** [review]
All of things seem to work for me. Required deep testing of different parts (all parts which depend on the events query of backend)

@abhiramtilakiiit Please do the deep testing.

**Review by Dileepadari — COMMENTED** [review]
Everything is verified, different pages and different users and modes verified. everything looks good and can be merged.

**Pull request merged**
